### PR TITLE
LF-47343 Fix icon being pixelated on some buttons

### PR DESCRIPTION
**Pull request by BenLewis-Seequent**
I initially tried to fix this by modifying our own style class, but that wasn't feasible as QStyleSheetStyle doesn't delegate enough to the base style.

### CODE REVIEW

**Review by JacobTinningSeequent — APPROVED** [review]

**Review by jeanbarendse — APPROVED** [review]

**Comment by ArthurGW** [comment]
> I initially tried to fix this by modifying our own style class, but that wasn't feasible as QStyleSheetStyle doesn't delegate enough to the base style.

Yeah, that's always been an annoying issue. I've been thinking recently that we should use QStyleSheetStyle as the base class for our style, then we can control what gets delegated to the base class and what doesn't.

Do you know why this works for other buttons? What makes the VO add button different?

**Comment by BenLewis-Seequent** [comment]
It only breaks because of the left alignment of that button(as it has a menu). Otherwise I think it falls through to QCommonStyle which correctly handles DPI.

**Review by henning-ruf — APPROVED** [review]

**Review by ArthurGW — APPROVED** [review]
I'll approve in the sense that the changes look fine.

I do wonder if it's necessary though, we can fix the issue by just modifying our app stylesheet to not hit the `if (rule.hasPosition() || rule.hasIcon())` check above:

```
QPushButton[buttonType=icon][hasMenu="true"],
QPushButton[buttonType=inlineIcon][hasMenu="true"] {
    padding: 9px 14px 9px 4px;
	width: 34px;
}
```

I guess that leaves a bug in that _could_ get hit in future.

**Comment by BenLewis-Seequent** [comment]
🤦 That does work. I will reject these PRs, as it is probably is worth fixing it in Qt unless we need to.

**Pull request closed without merging**
